DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS schedule;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  rank INTEGER
);

CREATE TABLE schedule (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  date TEXT NOT NULL,
  shift TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);